language: java
jdk:
- oraclejdk8
script: ant build
addons:
  sonarcloud:
    organization: "synonymthesis" # the key of the org you chose at step #3
    token:
      secure: SONAR_TOKEN
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
