language: java
jdk:
- oraclejdk9
script: mvn test -B
addons:
  sonarcloud:
    organization: synonymthesis
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
