language: java
jdk:
- oraclejdk8
script: mvn clean verify
addons:
  sonarcloud:
    organization: synonymthesis
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
